[tool.poetry]
name = "rinna-slackbot"
version = "0.1.0"
description = ""
authors = ["Koki Takahashi <hakatasiloving@gmail.com>"]
license = "Apache Licence 2.0"
readme = "README.md"
packages = [{ include = "**/*" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
slack-sdk = "^3.35.0"
regex = "^2024.11.6"
python-dotenv = "^1.1.0"
google-api-python-client = "^2.172.0"
firebase-admin = "^6.9.0"
pystray = "^0.19.4"
azure-cognitiveservices-vision-contentmoderator = "^1.0.0"
google-cloud-pubsub = "^2.30.0"
google-cloud-language = "^2.17.2"
datasets = {extras = ["audio"], version = "^2.21.0"}
evaluate = "^0.4.0"
transformers = "^4.43.2"
scikit-learn = "^1.7.0"
psutil = "^5.9.5"
pytest = "^8.4.1"
tokenizers = "^0.19.1"
pytest-mock = "^3.14.1"
torch = {version = "^2.1.2", source = "torch_cu121"}
vllm = "^0.3.3"
gstop = "^0.2.3"
llama-cpp-python = {version = "^0.3.4", source = "llama_cpp_cu121"}


[[tool.poetry.source]]
name = "torch_cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[[tool.poetry.source]]
name = "llama_cpp_cu121"
url = "https://abetlen.github.io/llama-cpp-python/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
