[tool.poetry]
name = "rinna-slackbot"
version = "0.1.0"
description = ""
authors = ["Koki Takahashi <hakatasiloving@gmail.com>"]
license = "Apache Licence 2.0"
readme = "README.md"
packages = [{ include = "**/*" }]

[tool.poetry.dependencies]
python = "^3.10"
slack-sdk = "^3.19.4"
regex = "^2022.10.31"
python-dotenv = "^0.21.0"
google-api-python-client = "^2.66.0"
firebase-admin = "^6.0.1"
pystray = "^0.19.4"
azure-cognitiveservices-vision-contentmoderator = "^1.0.0"
google-cloud-pubsub = "^2.13.11"
google-cloud-language = "^2.7.0"
datasets = "^2.9.0"
evaluate = "^0.4.0"
transformers = {git = "https://github.com/huggingface/transformers"}
scikit-learn = "^1.2.1"
psutil = "^5.9.5"
pytest = "^8.1.1"
tokenizers = "^0.15.2"
pytest-mock = "^3.12.0"
torch = {version = "^2.1.2", source = "cu121"}
vllm = "^0.3.3"


[[tool.poetry.source]]
name = "cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
